[package]
name = "iobot"
version = "0.1.0"
authors = ["Jakub Kądziołka <kuba@kadziolka.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
mathparser = { path = "mathparser" }
serde = "1"
serenity = "0.8"
toml = "0.5"

[workspace]
members = [
    "mathparser",
]
